// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// buildBufferIndicators_cpp
Rcpp::NumericVector buildBufferIndicators_cpp(Rcpp::NumericVector q, double g1, double g2, Rcpp::IntegerVector id);
RcppExport SEXP _bufferedThresholdPanel_buildBufferIndicators_cpp(SEXP qSEXP, SEXP g1SEXP, SEXP g2SEXP, SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type g1(g1SEXP);
    Rcpp::traits::input_parameter< double >::type g2(g2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type id(idSEXP);
    rcpp_result_gen = Rcpp::wrap(buildBufferIndicators_cpp(q, g1, g2, id));
    return rcpp_result_gen;
END_RCPP
}
// buildBufferIndicators3_cpp
Rcpp::IntegerVector buildBufferIndicators3_cpp(Rcpp::NumericVector q, double rL1, double rU1, double rL2, double rU2, Rcpp::IntegerVector id);
RcppExport SEXP _bufferedThresholdPanel_buildBufferIndicators3_cpp(SEXP qSEXP, SEXP rL1SEXP, SEXP rU1SEXP, SEXP rL2SEXP, SEXP rU2SEXP, SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type rL1(rL1SEXP);
    Rcpp::traits::input_parameter< double >::type rU1(rU1SEXP);
    Rcpp::traits::input_parameter< double >::type rL2(rL2SEXP);
    Rcpp::traits::input_parameter< double >::type rU2(rU2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type id(idSEXP);
    rcpp_result_gen = Rcpp::wrap(buildBufferIndicators3_cpp(q, rL1, rU1, rL2, rU2, id));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bufferedThresholdPanel_buildBufferIndicators_cpp", (DL_FUNC) &_bufferedThresholdPanel_buildBufferIndicators_cpp, 4},
    {"_bufferedThresholdPanel_buildBufferIndicators3_cpp", (DL_FUNC) &_bufferedThresholdPanel_buildBufferIndicators3_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_bufferedThresholdPanel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
