# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
#' @param q Threshold variable (original scale, not demeaned)
#' @param g1 Lower buffer boundary (rL)
#' @param g2 Upper buffer boundary (rU)
#' @param id Integer panel identifiers (converted in R wrapper)
#' @return Numeric vector: 0 = regime 1, 1 = regime 2
buildBufferIndicators_cpp <- function(q, g1, g2, id) {
    .Call(`_bufferedThresholdPanel_buildBufferIndicators_cpp`, q, g1, g2, id)
}

#' @noRd
#' @param q Threshold variable (original scale, not demeaned)
#' @param rL1 Lower boundary of buffer zone 1
#' @param rU1 Upper boundary of buffer zone 1
#' @param rL2 Lower boundary of buffer zone 2 (must be > rU1)
#' @param rU2 Upper boundary of buffer zone 2
#' @param id Integer panel identifiers (converted in R wrapper)
#' @return Integer vector with values 1L, 2L, or 3L
buildBufferIndicators3_cpp <- function(q, rL1, rU1, rL2, rU2, id) {
    .Call(`_bufferedThresholdPanel_buildBufferIndicators3_cpp`, q, rL1, rU1, rL2, rU2, id)
}

